# Generated by Django 3.0.7 on 2020-07-12 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnip',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(700), django.core.validators.MinValueValidator(0)]),
        ),
    ]
