# Generated by Django 3.0.7 on 2020-07-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackerapp', '0003_auto_20200714_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnip',
            name='user',
        ),
        migrations.AddField(
            model_name='turnip',
            name='resident',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
