# Generated by Django 3.0.7 on 2020-07-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_auto_20200714_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnip',
            old_name='user',
            new_name='resident',
        ),
    ]
