# Generated by Django 3.0.7 on 2020-07-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_auto_20200714_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnip',
            old_name='resident',
            new_name='user',
        ),
    ]
