# Generated by Django 3.0.7 on 2020-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0008_zingchartconfig_zingchartseriesdata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZingChartSeriesData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'zingchart_data_2',
            },
        ),
    ]
